name: My First github page

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 22f3000713@ds.study.iitm.ac.in
        run: | # python
          echo "Hello world!"
